name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create config.js
        run: |
          echo "const firebaseConfig = {" > config.js
          echo "  apiKey: \"${{ secrets.FIREBASE_API_KEY }}\"," >> config.js
          echo "  authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> config.js
          echo "  projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> config.js
          echo "  storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> config.js
          echo "  messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> config.js
          echo "  appId: \"${{ secrets.FIREBASE_APP_ID }}\"" >> config.js
          echo "};" >> config.js
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
